
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniCpp.js
 */

#include "RNMapsSpecs.h"

namespace facebook::react {

static facebook::jsi::Value __hostFunction_NativeAirMapsModuleSpecJSI_getCamera(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getCamera", "(DLcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeAirMapsModuleSpecJSI_getMarkersFrames(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getMarkersFrames", "(DZLcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeAirMapsModuleSpecJSI_getMapBoundaries(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getMapBoundaries", "(DLcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeAirMapsModuleSpecJSI_takeSnapshot(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "takeSnapshot", "(DLjava/lang/String;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeAirMapsModuleSpecJSI_getAddressFromCoordinates(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getAddressFromCoordinates", "(DLcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeAirMapsModuleSpecJSI_getPointForCoordinate(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getPointForCoordinate", "(DLcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeAirMapsModuleSpecJSI_getCoordinateForPoint(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getCoordinateForPoint", "(DLcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

NativeAirMapsModuleSpecJSI::NativeAirMapsModuleSpecJSI(const JavaTurboModule::InitParams &params)
  : JavaTurboModule(params) {
  methodMap_["getCamera"] = MethodMetadata {1, __hostFunction_NativeAirMapsModuleSpecJSI_getCamera};
  methodMap_["getMarkersFrames"] = MethodMetadata {2, __hostFunction_NativeAirMapsModuleSpecJSI_getMarkersFrames};
  methodMap_["getMapBoundaries"] = MethodMetadata {1, __hostFunction_NativeAirMapsModuleSpecJSI_getMapBoundaries};
  methodMap_["takeSnapshot"] = MethodMetadata {2, __hostFunction_NativeAirMapsModuleSpecJSI_takeSnapshot};
  methodMap_["getAddressFromCoordinates"] = MethodMetadata {2, __hostFunction_NativeAirMapsModuleSpecJSI_getAddressFromCoordinates};
  methodMap_["getPointForCoordinate"] = MethodMetadata {2, __hostFunction_NativeAirMapsModuleSpecJSI_getPointForCoordinate};
  methodMap_["getCoordinateForPoint"] = MethodMetadata {2, __hostFunction_NativeAirMapsModuleSpecJSI_getCoordinateForPoint};
}
static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_areTermsAccepted(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "areTermsAccepted", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_showTermsAndConditionsDialog(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "showTermsAndConditionsDialog", "(Ljava/lang/String;Ljava/lang/String;ZLcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_resetTermsAccepted(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "resetTermsAccepted", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_initializeNavigationSession(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "initializeNavigationSession", "(ZDLcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_cleanup(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "cleanup", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_setDestinations(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "setDestinations", "(Lcom/facebook/react/bridge/ReadableArray;Lcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_continueToNextDestination(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "continueToNextDestination", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_clearDestinations(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "clearDestinations", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_startGuidance(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "startGuidance", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_stopGuidance(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "stopGuidance", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_setSpeedAlertOptions(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "setSpeedAlertOptions", "(Lcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_setAbnormalTerminatingReportingEnabled(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "setAbnormalTerminatingReportingEnabled", "(Z)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_setAudioGuidanceType(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "setAudioGuidanceType", "(DLcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_setAudioGuidanceSettings(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "setAudioGuidanceSettings", "(Lcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_setBackgroundLocationUpdatesEnabled(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "setBackgroundLocationUpdatesEnabled", "(Z)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_setTurnByTurnLoggingEnabled(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, VoidKind, "setTurnByTurnLoggingEnabled", "(Z)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_getCurrentRouteSegment(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getCurrentRouteSegment", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_getRouteSegments(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getRouteSegments", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_getCurrentTimeAndDistance(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getCurrentTimeAndDistance", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_getTraveledPath(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getTraveledPath", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_getNavSDKVersion(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "getNavSDKVersion", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_stopUpdatingLocation(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "stopUpdatingLocation", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_startUpdatingLocation(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "startUpdatingLocation", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_simulateLocation(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "simulateLocation", "(Lcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_resumeLocationSimulation(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "resumeLocationSimulation", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_pauseLocationSimulation(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "pauseLocationSimulation", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_simulateLocationsAlongExistingRoute(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "simulateLocationsAlongExistingRoute", "(Lcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

static facebook::jsi::Value __hostFunction_NativeRNMapsNavModuleSpecJSI_stopLocationSimulation(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "stopLocationSimulation", "(Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

NativeRNMapsNavModuleSpecJSI::NativeRNMapsNavModuleSpecJSI(const JavaTurboModule::InitParams &params)
  : JavaTurboModule(params) {
  methodMap_["areTermsAccepted"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_areTermsAccepted};
  methodMap_["showTermsAndConditionsDialog"] = MethodMetadata {4, __hostFunction_NativeRNMapsNavModuleSpecJSI_showTermsAndConditionsDialog};
  methodMap_["resetTermsAccepted"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_resetTermsAccepted};
  methodMap_["initializeNavigationSession"] = MethodMetadata {2, __hostFunction_NativeRNMapsNavModuleSpecJSI_initializeNavigationSession};
  methodMap_["cleanup"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_cleanup};
  methodMap_["setDestinations"] = MethodMetadata {4, __hostFunction_NativeRNMapsNavModuleSpecJSI_setDestinations};
  methodMap_["continueToNextDestination"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_continueToNextDestination};
  methodMap_["clearDestinations"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_clearDestinations};
  methodMap_["startGuidance"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_startGuidance};
  methodMap_["stopGuidance"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_stopGuidance};
  methodMap_["setSpeedAlertOptions"] = MethodMetadata {1, __hostFunction_NativeRNMapsNavModuleSpecJSI_setSpeedAlertOptions};
  methodMap_["setAbnormalTerminatingReportingEnabled"] = MethodMetadata {1, __hostFunction_NativeRNMapsNavModuleSpecJSI_setAbnormalTerminatingReportingEnabled};
  methodMap_["setAudioGuidanceType"] = MethodMetadata {1, __hostFunction_NativeRNMapsNavModuleSpecJSI_setAudioGuidanceType};
  methodMap_["setAudioGuidanceSettings"] = MethodMetadata {1, __hostFunction_NativeRNMapsNavModuleSpecJSI_setAudioGuidanceSettings};
  methodMap_["setBackgroundLocationUpdatesEnabled"] = MethodMetadata {1, __hostFunction_NativeRNMapsNavModuleSpecJSI_setBackgroundLocationUpdatesEnabled};
  methodMap_["setTurnByTurnLoggingEnabled"] = MethodMetadata {1, __hostFunction_NativeRNMapsNavModuleSpecJSI_setTurnByTurnLoggingEnabled};
  methodMap_["getCurrentRouteSegment"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_getCurrentRouteSegment};
  methodMap_["getRouteSegments"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_getRouteSegments};
  methodMap_["getCurrentTimeAndDistance"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_getCurrentTimeAndDistance};
  methodMap_["getTraveledPath"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_getTraveledPath};
  methodMap_["getNavSDKVersion"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_getNavSDKVersion};
  methodMap_["stopUpdatingLocation"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_stopUpdatingLocation};
  methodMap_["startUpdatingLocation"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_startUpdatingLocation};
  methodMap_["simulateLocation"] = MethodMetadata {1, __hostFunction_NativeRNMapsNavModuleSpecJSI_simulateLocation};
  methodMap_["resumeLocationSimulation"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_resumeLocationSimulation};
  methodMap_["pauseLocationSimulation"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_pauseLocationSimulation};
  methodMap_["simulateLocationsAlongExistingRoute"] = MethodMetadata {1, __hostFunction_NativeRNMapsNavModuleSpecJSI_simulateLocationsAlongExistingRoute};
  methodMap_["stopLocationSimulation"] = MethodMetadata {0, __hostFunction_NativeRNMapsNavModuleSpecJSI_stopLocationSimulation};
  eventEmitterMap_["onLocationChanged"] = std::make_shared<AsyncEventEmitter<folly::dynamic>>();
  eventEmitterMap_["onArrival"] = std::make_shared<AsyncEventEmitter<folly::dynamic>>();
  eventEmitterMap_["onRemainingTimeOrDistanceChanged"] = std::make_shared<AsyncEventEmitter<folly::dynamic>>();
  eventEmitterMap_["onRouteChanged"] = std::make_shared<AsyncEventEmitter<folly::dynamic>>();
  eventEmitterMap_["onReroutingRequestedByOffRoute"] = std::make_shared<AsyncEventEmitter<folly::dynamic>>();
  eventEmitterMap_["onStartGuidance"] = std::make_shared<AsyncEventEmitter<folly::dynamic>>();
  eventEmitterMap_["onTurnByTurn"] = std::make_shared<AsyncEventEmitter<folly::dynamic>>();
  eventEmitterMap_["onRawLocationChanged"] = std::make_shared<AsyncEventEmitter<folly::dynamic>>();
  eventEmitterMap_["onTrafficUpdated"] = std::make_shared<AsyncEventEmitter<folly::dynamic>>();
  eventEmitterMap_["logDebugInfo"] = std::make_shared<AsyncEventEmitter<folly::dynamic>>();
  configureEventEmitterCallback();
}

std::shared_ptr<TurboModule> RNMapsSpecs_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params) {
  if (moduleName == "RNMapsAirModule") {
    return std::make_shared<NativeAirMapsModuleSpecJSI>(params);
  }
  if (moduleName == "RNMapsNavModule") {
    return std::make_shared<NativeRNMapsNavModuleSpecJSI>(params);
  }
  return nullptr;
}

} // namespace facebook::react
